# Generated by Django 4.2.11 on 2024-04-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to='university.student'),
        ),
        migrations.DeleteModel(
            name='Enrolled',
        ),
    ]
