# Generated by Django 4.2.11 on 2024-04-08 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_group_note_page_user_delete_course_delete_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to='university.user'),
        ),
        migrations.AlterField(
            model_name='group',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to='university.user'),
        ),
    ]
